name: build and deploy

on:
  push:
    branches: [ main ]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reusable-build:
    name: build
    uses: vishalmamidi/workflows/.github/workflows/build-gradle-native.yml@main
    secrets: inherit
